// Auto-generated index file for tdz_js/examples/ - DO NOT EDIT MANUALLY
// Generated by index-generator.py
// Run: python3 index-generator.py to regenerate

export {
  createApiKeyAuthMiddleware,
  requireRole,
  requireUserContext
} from './api_ex_3.js';
export {
  FileReaderTool,
  TextAnalyzerTool,
  demonstrateFileReader
} from './base_ex_1.js';
export { WeatherTool } from './base_ex_2.js';
export { authenticateToken } from './chunking_ex_1.js';
export {
  createDevelopmentTasks,
  demonstrateSemanticSearch as chunking_ex_3_demonstrateSemanticSearch,
  demonstrateTagFeatures,
  demonstrateTaskWorkflow,
  setupDevProject
} from './chunking_ex_3.js';
export { DevelopmentWorkflowExample } from './chunking_ex_5.js';
export { CodeReviewAgent } from './cli_ex_3.js';
export { demonstrateSemanticSearch as emb_ex_1_demonstrateSemanticSearch } from './emb_ex_1.js';
export { SmartTaskManager } from './error_ex_3.js';
export {
  advancedTaskManagementDemo,
  demonstrateCrossContentRelationships
} from './main_ex_3.js';
export { performAdvancedMigration } from './migration_ex_3.js';
export {
  Reminder,
  ReminderManagerExt,
  ReminderPriority,
  ReminderStatistics,
  ReminderStatus,
  ReminderUpdate,
  parseReminderFormat
} from './reminder_ex_5.js';
export { AdvancedTaskManager } from './server_ex_3.js';
export {
  demonstrateSearchCapabilities,
  demonstrateSmartRecommendations,
  demonstrateTagManagement,
  establishTagRelationships,
  setupDevelopmentTags,
  simulateTagUsage
} from './tags_ex_3.js';
export { TodoziProjectManager } from './tdz_ex_3.js';
export { demonstrateAdvancedTagManagement } from './tdz_tls_ex_3.js';
export {
  runQueueTests,
  test_queue_collection_filtering,
  test_queue_item_creation,
  test_queue_item_status_transitions,
  test_queue_json_serialization,
  test_queue_priority_ordering,
  test_queue_project_filtering,
  test_queue_session_error_handling,
  test_queue_session_lifecycle
} from './tests_ex_3.js';
export { AdvancedSearchEngine } from './todozi_exe_ex_3.js';
export { runTodoziExample5 } from './todozi_exe_ex_5.js';
export {
  createProjectDashboard,
  manageDevProject
} from './todozi_tool_ex_3.js';
export {
  MockEmbeddingService,
  TaskDashboard,
  runTaskDashboard
} from './tui_ex_1.js';
export {
  addDevelopmentTasks,
  demonstrateSemanticSearch as tui_ex_3_demonstrateSemanticSearch,
  demonstrateTaskClustering,
  generateProjectSummary,
  processNaturalLanguageInput,
  setupDevelopmentProject,
  updateTaskProgress as tui_ex_3_updateTaskProgress
} from './tui_ex_3.js';
export {
  areAllDependenciesComplete,
  createProjectWithDependencies,
  findDependentTasks,
  setupTaskQueue,
  updateTaskProgress as types_ex_3_updateTaskProgress
} from './types_ex_3.js';

// End of auto-generated file