/* Todozi C FFI Bindings
 * Generated by cbindgen
 */


#ifndef TODOZI_FFI_H
#define TODOZI_FFI_H

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is auto-generated */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* TODOZI_FFI_H */
