#include "emb.h"
#include <stdio.h>
#include <string.h>

int main(void) {
    // Initialize the embedding service with default configuration
    struct TodoziEmbeddingConfig config = config_default();
    struct TodoziEmbeddingTool* tool = tool_new(config);
    
    if (!tool) {
        printf("Failed to create embedding tool\n");
        config_free(&config);
        return 1;
    }
    
    // Initialize the service
    if (tool_initialize(tool) != EMB_SUCCESS) {
        printf("Failed to initialize embedding service\n");
        tool_free(tool);
        config_free(&config);
        return 1;
    }
    
    printf("Semantic Search Example\n");
    printf("=======================\n");
    
    // Create sample task embeddings (in practice, these would be generated by the model)
    struct TodoziEmbeddingCache* task1 = malloc(sizeof(struct TodoziEmbeddingCache));
    task1->content_id = string_new("task1");
    task1->text_content = string_new("Implement user authentication system");
    task1->vector = vec_new_with_capacity(3);
    vec_push(&task1->vector, (void*)1.0f);
    vec_push(&task1->vector, (void*)0.5f);
    vec_push(&task1->vector, (void*)0.2f);
    task1->created_at = time(NULL);
    task1->ttl_seconds = 3600;
    vec_push(&task1->tags, strdup("backend"));
    vec_push(&task1->tags, strdup("security"));
    
    struct TodoziEmbeddingCache* task2 = malloc(sizeof(struct TodoziEmbeddingCache));
    task2->content_id = string_new("task2");
    task2->text_content = string_new("Design responsive UI components");
    task2->vector = vec_new_with_capacity(3);
    vec_push(&task2->vector, (void*)0.2f);
    vec_push(&task2->vector, (void*)0.8f);
    vec_push(&task2->vector, (void*)0.9f);
    task2->created_at = time(NULL);
    task2->ttl_seconds = 3600;
    vec_push(&task2->tags, strdup("frontend"));
    vec_push(&task2->tags, strdup("design"));
    
    // Add tasks to cache
    cache_insert(tool->service->cache, "task1", task1);
    cache_insert(tool->service->cache, "task2", task2);
    
    // Perform semantic search
    const char* query = "Create login page";
    struct Vec results = service_semantic_search(tool->service, query, NULL, 5);
    
    printf("Search query: \"%s\"\n", query);
    printf("Found %zu similar tasks:\n", results.size);
    
    // In a real implementation, results would contain similarity scores
    printf("1. %s\n", task1->text_content.data);
    printf("2. %s\n", task2->text_content.data);
    
    // Find similar tasks
    struct Vec similar = service_find_similar_tasks(tool->service, "User login functionality", 3);
    printf("\nSimilar tasks to \"User login functionality\": %zu found\n", similar.size);
    
    // Cleanup
    cache_entry_free(task1);
    cache_entry_free(task2);
    vec_free(&results);
    vec_free(&similar);
    tool_free(tool);
    config_free(&config);
    
    return 0;
}
